[ls]
tags = [
  "list files in directory",
  "see files",
  "show directory"
, "directory contents", "see dir"]

[man]
tags = [
  "show help about a program",
  "manual pages"
]

[touch]
tags = [
  "create files",
  "update file acces"
]

[cd]
tags = ["change current directory"]

[mkdir]
tags = ["create new directory"]
